name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            php-versions: ['7.4', '8.0']
            composer-flags: ["--prefer-lowest", ""]
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
           php-version: ${{ matrix.php-versions }}
    - name: Install Dependencies
      run: composer update ${composer-flags} --no-interaction --prefer-source
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
